### ISSUE TITLE
Doesn't start, unhandled exception in Event Viewer

### ISSUE THREAD

**Issue by sgcdialler** [Zettymaster/HUDColorChanger#1]
Faulting application name: HUDColorChanger.exe, version: 1.0.0.0, time stamp: 0x5b5bd96a
Faulting module name: KERNELBASE.dll, version: 6.1.7601.24168, time stamp: 0x5b1aa7a9
Exception code: 0xe0434352
Fault offset: 0x0000c54f
Faulting process id: 0x26c0
Faulting application start time: 0x01d4327f487a7705
Faulting application path: D:\Users\[username]\Desktop\HUDColorChanger\HUDColorChanger.exe
Faulting module path: C:\Windows\syswow64\KERNELBASE.dll
Report Id: 874d1f4c-9e72-11e8-9065-005056c00008

Application: HUDColorChanger.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Xml.XmlException
   at System.Xml.XmlTextReaderImpl.Throw(System.Exception)
   at System.Xml.XmlTextReaderImpl.Throw(System.String, System.String)
   at System.Xml.XmlTextReaderImpl.ThrowUnclosedElements()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.Linq.XContainer.ReadContentFrom(System.Xml.XmlReader)
   at System.Xml.Linq.XContainer.ReadContentFrom(System.Xml.XmlReader, System.Xml.Linq.LoadOptions)
   at System.Xml.Linq.XDocument.Load(System.Xml.XmlReader, System.Xml.Linq.LoadOptions)
   at System.Xml.Linq.XDocument.Load(System.String, System.Xml.Linq.LoadOptions)
   at System.Xml.Linq.XDocument.Load(System.String)
   at HUDColorChanger.MainWindow.InitializeXML()
   at HUDColorChanger.MainWindow..ctor()

Exception Info: System.Windows.Markup.XamlParseException
   at System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri)
   at System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(System.IO.Stream, System.Windows.Markup.ParserContext)
   at System.Windows.Application.LoadComponent(System.Uri, Boolean)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at HUDColorChanger.App.Main()

**Comment by sgcdialler** [comment]
Strange, for some reason now when I execute it, it opens just fine.

I did attempt to open in VS2013, and got ![this error.](https://user-images.githubusercontent.com/23480194/44006763-d7cb4442-9e57-11e8-9184-db7163273c70.png) I would list .NET 4.7 as a prerequisite, by the way. I ran the online .NET 4.7 installer just to be sure, but it was already installed, then I've tried executing the program again and it seems fine now.

**Comment by Zettymaster** [comment]
Seems like that is the culprit. I did everything in VS 2017, so it seems VS 2013 does either not handle the new project files or C# language features too well...

**Comment by sgcdialler** [comment]
VS2013 is fine, for some reason .NET 4.7 is not available as a target option on that machine (Win7). The project opened fine in 2017 on a different machine (Win10). There is something else that might have been the culprit but I want to experiment with it tonight--potential conflict if you're using EDFX.

**Comment by sgcdialler** [comment]
Issue only occurs if another editor has already modified the GraphicsConfigurationOverride.xml file.
